name: Frontend CI/CD

on:
  push:
    branches:
      - Interview-User

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GKE_PROJECT }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Kubernet/frontend-cert.yaml
          kubectl apply -f Kubernet/user-frontend-deployment.yaml
          kubectl apply -f Kubernet/frontend-service.yaml
          kubectl apply -f Kubernet/frontend-ingress.yaml